repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(cpp|hpp|h)$
        stages: [pre-commit]

      - id: clang-tidy
        name: clang-tidy
        entry: run-clang-tidy -p build/linux-debug
        language: system
        files: \.(cpp|hpp)$
        pass_filenames: false
        stages: [pre-commit]
